stages:
  - install
  - lint
  - build
  - test
  - secret-detection

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

# Backend – Node.js + TypeScript
backend:install:
  stage: install
  image: node:20-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-backend
    paths:
      - backend/node_modules/
  before_script:
    - cd backend
  script:
    - npm ci
  artifacts:
    paths:
      - backend/node_modules/
    expire_in: 1h
  rules:
    - changes:
        - backend/**/*

backend:lint:
  stage: lint
  image: node:20-alpine
  needs: ["backend:install"]
  before_script:
    - cd backend
  script:
    - npm run lint
  rules:
    - changes:
        - backend/**/*

backend:build:
  stage: build
  image: node:20-alpine
  needs: ["backend:install"]
  before_script:
    - cd backend
  script:
    - npm run build
  rules:
    - changes:
        - backend/**/*

backend:test:
  stage: test
  image: node:20-alpine
  needs: ["backend:install"]
  before_script:
    - cd backend
  script:
    - npm test
  rules:
    - changes:
        - backend/**/*

# Frontend – Angular
frontend:install:
  stage: install
  image: node:20-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-frontend
    paths:
      - frontend/node_modules/
  before_script:
    - cd frontend
  script:
    - npm ci
  artifacts:
    paths:
      - frontend/node_modules/
    expire_in: 1h
  rules:
    - changes:
        - frontend/**/*

frontend:lint:
  stage: lint
  image: node:20-alpine
  needs: ["frontend:install"]
  before_script:
    - cd frontend
  script:
    - npm run lint
  rules:
    - changes:
        - frontend/**/*

frontend:build:
  stage: build
  image: node:20-alpine
  needs: ["frontend:install"]
  before_script:
    - cd frontend
  script:
    - npm run build -- --configuration production
  rules:
    - changes:
        - frontend/**/*

frontend:test:
  stage: test
  image: node:20-alpine
  needs: ["frontend:install"]
  before_script:
    - cd frontend
    - apk add --no-cache chromium
  script:
    - npm test -- --watch=false --browsers=ChromeHeadless
  variables:
    CHROME_BIN: /usr/bin/chromium-browser
  rules:
    - changes:
        - frontend/**/*

sast:
  stage: test

secret_detection:
  stage: secret-detection
